/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Btn: typeof import('./components/Btn.vue')['default']
    Chip: typeof import('./components/Chip.vue')['default']
    ColorSwatch: typeof import('./components/ColorSwatch.vue')['default']
    Dragzone: typeof import('./components/Dragzone.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    Indicator: typeof import('./components/Indicator.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    NotificationSystem: typeof import('./components/NotificationSystem.vue')['default']
    Paper: typeof import('./components/Paper.vue')['default']
    PinInput: typeof import('./components/PinInput.vue')['default']
    Progress: typeof import('./components/Progress.vue')['default']
    RokuProvider: typeof import('./components/RokuProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select.vue')['default']
    Slider: typeof import('./components/Slider.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
    ThemeProvider: typeof import('./components/ThemeProvider.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
  }
}
