/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AspectRatio: typeof import('./components/AspectRatio.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Btn: typeof import('./components/Btn.vue')['default']
    BtnGroup: typeof import('./components/BtnGroup.vue')['default']
    ChatContainer: typeof import('./components/ChatContainer.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ChatSystem: typeof import('./components/ChatSystem.vue')['default']
    Chip: typeof import('./components/Chip.vue')['default']
    ColorInput: typeof import('./components/ColorInput.vue')['default']
    ColorSwatch: typeof import('./components/ColorSwatch.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    Dropzone: typeof import('./components/Dropzone.vue')['default']
    FullscreenOverlay: typeof import('./components/FullscreenOverlay.vue')['default']
    Image: typeof import('./components/Image.vue')['default']
    Indicator: typeof import('./components/Indicator.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    NotificationSystem: typeof import('./components/NotificationSystem.vue')['default']
    Overlay: typeof import('./components/Overlay.vue')['default']
    Paper: typeof import('./components/Paper.vue')['default']
    PinInput: typeof import('./components/PinInput.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    Progress: typeof import('./components/Progress.vue')['default']
    Rating: typeof import('./components/Rating.vue')['default']
    RokuProvider: typeof import('./components/RokuProvider.vue')['default']
    SchemeSwitch: typeof import('./components/SchemeSwitch.vue')['default']
    ScrollArea: typeof import('./components/ScrollArea.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    SelectArea: typeof import('./components/SelectArea.vue')['default']
    Slider: typeof import('./components/Slider.vue')['default']
    Switch: typeof import('./components/Switch.vue')['default']
    TabItem: typeof import('./components/TabItem.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    Tag: typeof import('./components/Tag.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
    ThemeProvider: typeof import('./components/ThemeProvider.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
    TreeList: typeof import('./components/TreeList.vue')['default']
  }
}
